language: python
branches:
  only:
  - master
addons:
  chrome: stable
python:
- 3.6.1
env:
- DJANGO_VERSION=1.11.6
install:
- pip install -r requirements.txt
- sudo apt-get install chromium-chromedriver
- sudo ln -s /usr/lib/chromium-browser/chromedriver /usr/bin/chromedriver
- sudo apt-get install wkhtmltopdf
script:
- python3 manage.py test
deploy:
  provider: heroku
  api_key:
    secure: FPwQ8fgOq/AzjAd9BufvHwHy8xpmaE6JIdL3skRiWPzlbqJ1CXwQi84aRzIAR6hKLnXqMnYbF7I0/rjHBXWe82NuJvhCgkz8M8y6NughlPSUt22kfw3DH8Xqd4OfSnMu2OONMc13FIThw+USoNAsWq5rFJzitXmAbVStBX3Xot8hpKjIatmnkTJrt+208gNcxClA+Z0J8WD0KTJ/vpWamFOe2LStqYM3CIogbl0wpm12obMHGHkZ26gw6WEklw2Cw17saGe/5Cv7o5gCmasFBBTeqhGbCt4XrJwziStPAgKL0R9bTf/j+JDLJlr/tnP9Fxf6B8mUf4PqcBAO1r5Hl8goPUKPmn6UhY/tTrVRMCBxdcuaghhSKhYwg+u+81b0d/+o4xAMX/ZYJ+8jv3ew7nzAB9J8+R2qtttH8E6Tlf16PpGtcw/OTV0mjMO50aVuXA3m1nlm+aixOA5eGoDW4RFYo/L2DYzY23vQxURKWNVElbTS6XMknJt8qXdV+By7DdUUa+x6FoH3Mdyugvkuy5HViZp9ngIthQpLBpB/n/xGWDRGcPQyPi4XySfwmQsGRt9SNLyCqxjMIXXznCzL6zFMqhA8fUa3/5AXzbPOo0kEgc/WMrIAcOvVrXNjszC3RhPHAapuejYr8ZX/EE2Y1uTnGb6B0FrcYs6gRdT9fnY=
  app: accounting-for-friends
  on:
    repo: wiedzmac/accounting_for_friends
