# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 16:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='avatar',
            field=models.URLField(default=None),
        ),
    ]
