# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 16:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='avatar',
            field=models.URLField(default=None, null=True),
        ),
    ]
