# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-04 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20171026_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='avatar',
            field=models.URLField(default='img/anonymous_user.png'),
        ),
    ]
