# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-05 13:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20171104_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='currency',
            field=models.CharField(choices=[('EUR', 'EURO'), ('USD', 'US DOLLAR'), ('PLN', 'POLISH ZLOTY'), ('INR', 'INDIAN RUPEE')], default='EUR', max_length=3),
        ),
    ]
