# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-05 18:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_account_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='currency',
            field=models.CharField(choices=[('EUR', 'Euro'), ('USD', 'US dollar'), ('PLN', 'Polish złoty'), ('INR', 'Indian rupee')], default='EUR', max_length=3),
        ),
    ]
