# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-22 05:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
        ('accounts', '0001_initial'),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='transaction',
            name='created',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='transaction',
            name='creator',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator', to='accounts.Account'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='finished',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='groups.UserGroup'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='payee',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payee', to='accounts.Account'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='payer',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payer', to='accounts.Account'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('O', 'OPEN'), ('C', 'CLOSED')], default='O', max_length=1),
        ),
    ]
