# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-04 10:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_auto_20171022_0549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='payee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payee', to='accounts.Account'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='payer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payer', to='accounts.Account'),
        ),
    ]
