# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-05 13:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_auto_20171104_1053'),
        ('transactions', '0003_auto_20171104_1023'),
    ]

    operations = [
    ]
