# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-08 08:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_merge_20171105_1345'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('currency', models.CharField(choices=[('USD', 'US DOLLAR'), ('EUR', 'EURO'), ('INR', 'INDIAN RUPEE'), ('PLN', 'POLISH ZLOTY')], max_length=3)),
            ],
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='amount',
        ),
        migrations.AddField(
            model_name='transaction',
            name='expense',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='transactions.Expense'),
        ),
    ]
