# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 19:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergroup',
            name='group_name',
            field=models.CharField(default='', max_length=80),
        ),
    ]
