# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-08 08:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='status',
            field=models.CharField(choices=[('TC', 'TRANSACTION CREATED'), ('TE', 'TRANSACTION EDITED'), ('TF', 'TRANSACTION FINISHED'), ('GA', 'ADDED TO GROUP'), ('GR', 'REMOVED FROM GROUP'), ('GD', 'GROUP DELETED')], max_length=2),
        ),
    ]
